### ISSUE TITLE
how to add my own author cert?

### ISSUE THREAD

**Issue by elnoelsi** [jeppevinkel/jellyfin-tizen-builds#1]
installation fails since the cert used on the wgt is yours and its only valid for your tv

**Comment by alexmacdonald5290** [comment]
Worked for me without a cert by using the CLI

**Comment by elnoelsi** [comment]
> Worked for me without a cert by using the CLI
what command did you use?

**Comment by jeppevinkel** [comment]
You should be able to just follow the instructions in the [readme](https://github.com/jeppevinkel/jellyfin-tizen-builds) without needing a cert. This build uses a generic cert that isn't specific to any TV.

**Comment by elnoelsi** [comment]
cant confirm 100%, but im pretty sure it was failing cause i already had the app installed with its own certs. 

Arrived at this conclusion after doing my own build with different certs from a new tizen studio installation and the wgt install would fail. Removing the app from tv allowd the wgt to be installed against just fine.

Perhaps would be worth to mention it on readme.

**Comment by elnoelsi** [comment]
cant confirm 100%, but im pretty sure it was failing cause i already had the app installed with its own certs.

Arrived at this conclusion after doing my own build with different certs from a new tizen studio installation and the wgt install would fail. Removing the app from tv allowd the wgt to be installed against just fine.

Perhaps would be worth to mention it on readme.

**Comment by clbx** [comment]
Had the same issue, removing the old app solves that error. 

Removing it from the app bar is also not the same as removing it from the device, you need to actually go into the applications menu and remove it from there ~~hopefully I'll save someone else an hour of wondering why its not working~~

**Comment by jeppevinkel** [comment]
I've now added a comment about this to the readme
