### ISSUE TITLE
Jellyfin 10.8.10 released

### ISSUE THREAD

**Issue by zapotah** [jeppevinkel/jellyfin-tizen-builds#10]
Jellyfin has a critical security update released last month but your system has not built this version.

https://github.com/jellyfin/jellyfin-web/releases/tag/v10.8.10
https://github.com/jellyfin/jellyfin/releases/tag/v10.8.10

**Comment by jeppevinkel** [comment]
Apologies. I'll have a look later in the day to see if any parts of my pipeline has any errors.

**Comment by jeppevinkel** [comment]
Turns out a change in the jellyfin-web master branch has caused an issue that made my build fail. The latest build is now on 10.8.10
