### ISSUE TITLE
Install on Samsung TV

### ISSUE THREAD

**Issue by itchygrub** [jeppevinkel/jellyfin-tizen-builds#12]
Installed on samsung UA55KS8000.
via CLI
Did not work through windows app
Black screen when try to run

**Comment by jeppevinkel** [comment]
Any chance this could be related to issue #11 which I just fixed?

**Comment by consolecwby** [comment]
I am having same issue i get this when i run the command.
```
C:\tizen-studio\tools\ide>tizen install -n Jellyfin.wgt -t <UN50MU6300>
The syntax of the command is incorrect.
```
I downloaded the jellyfin.wgt file and placed it in the C:\tizen-studio\tools\ide\bin folder. Is this correct method?

I try to just install using the GUI tizen studio manager but i get some certificate error but i have never installed it before.

**Comment by jeppevinkel** [comment]
Remove the < ans > from your commands. Those only exist in the template command to indicate its a value you should replace.
