### ISSUE TITLE
Wont connect to server.

### ISSUE THREAD

**Issue by Arhu** [jeppevinkel/jellyfin-tizen-builds#15]
Hi, i tried to connect to the server using the ip, my redirects/domains and it just won't find it.
I tried to use the browser and that seemed to work fine so I think the problem is in the build.
Any tips or ideas?

**Comment by Orbitally** [comment]
Unfortunately, I wasn't able to figure out a fix for this but just thought I'd let you know this issue isn't just you and is happening to me as well.

**Comment by Arhu** [comment]
I have no idea how, but it works somehow. The ip from the DNS won't work, but the original ip works.

**Comment by Orbitally** [comment]
The original IP being the 192.168.xxx.xxx address of the Jellyfin server?

**Comment by Arhu** [comment]
Yes, but with the port included so: 192.168.xxx.xxx:port

The default port is 8096, but you may change it in the settings from the Jellyfin dashboard or by editing the config file.

**Comment by jeppevinkel** [comment]
Issues of this kind are probably more suited on https://github.com/jellyfin/jellyfin-tizen as I don't have anything to do with the code of the app. I only facilitate a way to get a build of the app.
