### ISSUE TITLE
Movie intro repeating

### ISSUE THREAD

**Issue by badmarques** [jeppevinkel/jellyfin-tizen-builds#16]
In some movies, at the beginning of the movie, the video reproduction repeats a previous short sequence.
This results in the intro of the film repeating (some seconds). 
This problem cause the subtitles to desync for the entire movie.

This does not happen on the web client (using a PC).

**Comment by jeppevinkel** [comment]
Issues during usage should be brought up in the official jellyfin-tizen repository, and I don't modify any files here. I only provide builds of the releases they make. https://github.com/jellyfin/jellyfin-tizen
