### ISSUE TITLE
large jump in file size without bump in version numbers or otherwise visible versioning

### ISSUE THREAD

**Issue by zapotah** [jeppevinkel/jellyfin-tizen-builds#18]
The build size suddenly jumped to 42Mb according to monitoring. Is something wrong or did something unwanted make it into the build?

**Comment by jeppevinkel** [comment]
I agree that does seem large. I don't know what could have changed since I'm directly building whatever is coming from the official jellyfin-tizen and jellyfin-web repositories, but I'll try investigating.

**Comment by jeppevinkel** [comment]
No changes in my build pipeline since the last small release, so that at least confirms it must be due to changes on Jellyfin's side.

**Comment by jeppevinkel** [comment]
It appears they've changed it up so the jellyfin-web build stores fonts in the build. I've modified the pipeline to set a variable now to use system fonts instead of bundling them.

**Comment by zapotah** [comment]
just to make sure you made the changes to everything you intended, only the master build came down to 11Mb, the others not so much.

**Comment by jeppevinkel** [comment]
I did notice, but I won't make a big deal out of those two for at least a couple versions since it's most likely just due to a mismatch between jellyfin-web and jellyfin-tizen. Since there is no official release versions of jellyfin-tizen, it's probably developed against the jellyfin-web master version and so the changes might not be applicable to the other two.

**Comment by jeppevinkel** [comment]
Hmm, after further consideration I'm reopening this again as it might be related to #19 since that issue is there with the only version that actually got smaller from my changes.

**Comment by coudu** [comment]
Hi,

for jellyfin-web 10.9+ (master) USE_SYSTEM_FONTS=1 is required to discard unused fonts and to reduce the size of the app when building Jellyfin Web.
but for jellyfin-web 10.8.z (release and pre-realease) you need to add DISCARD_UNUSED_FONTS=1 environment variable to discard unused fonts and to reduce the size of the app when preparing interface/building jellyfin-tizen.

also SKIP_PREPARE=1 can be omitted for 10.9+.

https://github.com/jellyfin/jellyfin-tizen#build-jellyfin-web
https://github.com/jellyfin/jellyfin-tizen#prepare-interface
