### ISSUE TITLE
Not installing 

### ISSUE THREAD

**Issue by Auriux123** [jeppevinkel/jellyfin-tizen-builds#21]
Any ideas how to fix issue?

C:\tizen-studio\tools\ide\bin>tizen install -n Jellyfin.wgt -t UE43RU7172UXXH
Transferring the package...
Transferred the package: C:\tizen-studio\tools\ide\bin\Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
was_install_app return WAS_TRUE
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] download failed[116]
spend time for wascmd is [29]ms
cmd_ret:0
Failed to install Tizen application.
Total time: 00:00:07.609

**Comment by Auriux123** [comment]
Used older version - worked like a charm. thank you

**Comment by Kraktoos** [comment]
I just spent an entire afternoon on this. Thank you. An older version (that weight like 10mb instead of the now usual 40mb) worked! Why would this be? What update of Jellyfin could have broken this?
