### ISSUE TITLE
this is not a problem but a wish

### ISSUE THREAD

**Issue by ks0002544** [jeppevinkel/jellyfin-tizen-builds#28]
this is not a problem but a wish
After deleting the viewed item, the page returns to the main menu. Is it possible to stay on the page from which the deletion occurred or to automatically re-read it?

**Comment by jeppevinkel** [comment]
I don't perform any changes to functionality in my repository. Any feature requests regarding the client should be directed to either https://github.com/jellyfin/jellyfin or https://github.com/jellyfin/jellyfin-tizen
