### ISSUE TITLE
Jellyfin fast forward function doesn't work.

### ISSUE THREAD

**Issue by LordJsus** [jeppevinkel/jellyfin-tizen-builds#30]
Hello,

The fast forward function in Jellyfin is not working properly. Neither direct playback nor rendering the videos make a difference. When I attempt to fast forward in a video, the playback remains stuck at the same point or jumps irregularly. This issue occurs across various videos and on different devices.

I have already tried restarting Jellyfin and experimenting with different browsers and devices, but to no avail. It seems to be a software-related problem, possibly caused by an update or configuration change.

Could you please investigate and resolve this issue? I am available for further information if needed.

Thank you.

**Comment by penguintamer** [comment]
This is the wrong repository for any issues with Jellyfin itself. They just build the Tizen release here.
If your UI issues happen only on Tizen, you want https://github.com/jellyfin/jellyfin-tizen
If your UI issues happen on multiple devices, you want https://github.com/jellyfin/jellyfin-web/issues
and if your issues are related to the server, not the UI, you want https://github.com/jellyfin/jellyfin

**Comment by jeppevinkel** [comment]
Thanks for providing the very helpful response penguintamer. I'll just close this issue since it doesn't belong here.
