### ISSUE TITLE
Provide a build for TrueHD audio support

### ISSUE THREAD

**Issue by absamue** [jeppevinkel/jellyfin-tizen-builds#32]
Per the following issue, it is possible to enable TrueHD audio by modifying tizen.js in jellyfin-tizen:
https://github.com/jellyfin/jellyfin-tizen/issues/226#issuecomment-1765771658

Since not all clients would need this, perhaps it should be a separate build.

**Comment by absamue** [comment]
For anyone that wants to run a build of their own, I slapped the steps from this repository into a Dockerfile, including the change needed
https://github.com/absamue/jellyfin-tizen-truehd-build

I have confirmed using this build provides Direct Playback for TrueHD audio files.

**Comment by jeppevinkel** [comment]
Hello, sorry for the slow response. I'm working on an update now to include it.
It will be part of a major rewrite of my build workflow that should make changes easier to make in the future by having a single build job that is just modified through a matrix strategy instead of much duplicate yaml.

**Comment by jeppevinkel** [comment]
I'm not sure my tv supports TrueHD. Is there any chance I could get you to try one of these builds? https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-04-28-2032

**Comment by jeppevinkel** [comment]
Per this comment, I doubt this really works even if the TV claims it does https://github.com/jellyfin/jellyfin-tizen/issues/226#issuecomment-2082167463

**Comment by jeppevinkel** [comment]
I'll close this under the assumption my TrueHD builds fulfill the need. Otherwise feel free to re-open.
