### ISSUE TITLE
Question: difference between Master and non-master 

### ISSUE THREAD

**Issue by Madaraxa** [jeppevinkel/jellyfin-tizen-builds#34]
The title says it all.
I use the file without Master or prerelease (which is like beta i guess).
But what is 'Master' in difference to the file without Master?

**Comment by jeppevinkel** [comment]
Master means that it builds directly the master branch of jellyfin-web, which means it will be the most bleeding edge version with the latest changes, but it could also be changes that might break functionality since it can be untested changes.
