### ISSUE TITLE
Intro skip integration

### ISSUE THREAD

**Issue by CvonB** [jeppevinkel/jellyfin-tizen-builds#35]
First of all, great job with this and thank you for a great product. 

Any plans on integrating [intro skip functionality](https://github.com/306bobby/intro-skipper) into this? If not, would you mind pointing me in the direction for development of tizen builds? I really have no clue where to start.

**Comment by CvonB** [comment]
Indeed the core functionality of it is, however the actual skip intro button is part of the jellyfin-web assets.

**Comment by jeppevinkel** [comment]
I try to keep these builds as close to stock as possible so changes on jellyfin/jellyfin-web and jellyfin/jellyfin-tizen won't break anything, but since there's a dedicated repository I've tried just adding a build option to build from other repositories. I've put over a test build now.

**Comment by jeppevinkel** [comment]
You can test one of the `intros` builds in this release https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-04-29-2058

**Comment by idarkalex** [comment]
> You can test one of the `intros` builds in this release https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-04-29-2058

I´ve tested this myself and I can confirm you that the button appears now and it is working as intended!

**Comment by CvonB** [comment]
The Devil works hard but jeppevinkel works harder. Awesome job, thank you.

**Comment by jeppevinkel** [comment]
You got here at a fortunate time. I've neglected this repository since last year, but spent a couple days fixing up everything and streamlining the build and release pipelines just now.
