### ISSUE TITLE
failed to construct 'Headers'

### ISSUE THREAD

**Issue by hossihub** [jeppevinkel/jellyfin-tizen-builds#36]
Tried installing the https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/download/2024-05-12-1523/Jellyfin-master.wgt. but get an error about "failed to construct headers" when opening the app on the TV.

**Comment by jeppevinkel** [comment]
I'm trying out a slightly different build config to see if that works, but I would hold off a bit on using 10.9.0 until there have been some updates to the official jellyfin-tizen repository.

I haven't personally upgraded my main server to 10.9.0 yes since I'm expected some kinks for the first release version.

**Comment by hossihub** [comment]
Can I find download url for the 10.8 version? Seem to get the new one each time

**Comment by jeppevinkel** [comment]
This one should work for 10.8 https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-05-04-1137

**Comment by hossihub** [comment]
Here’s the error from the app on the latest version: 

rror:%20Failed%20to%20construct%20'Headers'%3A%20No%20matching%20constructor%20signature.%20e%20(file%3A///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:22761)%0Aoader%20(file:///www/15434.028f60b4fcaf765c61da.chunk.js:1:5812)%0Av%20(file:///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:51494)%0Afile:///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:52270%0Ad%20(file:///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:730)%0AGenerator.%20%E2%80%B9anonymous%3E%20(file:///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:2072)%0AGenerator.next%20(file:///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:1159)%0Ato%20(file:///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:6633)%0At%20u%20(file:///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:6836)%0Ait%20file:///www/node_modules.@remix-run.router.33c9ecbab57840d1d963.chunk.js:2:6895

**Comment by hossihub** [comment]
I get the same issue if I try to use the browser (Samsung 2018 The Frame) and connect .

**Comment by jeppevinkel** [comment]
This is probably an issue upstream that I can't fix in my build pipeline since I'm not touching any of the actual code.
I'd like to follow this issue and see if a resolution is found. https://github.com/jellyfin/jellyfin-tizen/issues/258

**Comment by kslenker** [comment]
I found same issue but also found this -- https://github.com/remix-run/react-router/pull/11148

**Comment by cheat2win** [comment]
The **2024-05-20 16:47 PreRelease Version** fixes this issue, at least for me.

Thank you @jeppevinkel

**Comment by hossihub** [comment]
same here! thanx for help :)

**Comment by jeppevinkel** [comment]
Great that it worked out. I'll close this issue now then. In the mean time, I'll probably have to rethink how I do releases to minimize problems 😄

**Comment by ilteoood** [comment]
Hi guys, sorry to necropost on this.
I've just tried to install version 10.9.8 and it's still happening.
Do you have any advice to solve it?
