### ISSUE TITLE
Failed to install App

### ISSUE THREAD

**Issue by Dokman** [jeppevinkel/jellyfin-tizen-builds#4]
so the main problem is this one 

![image](https://user-images.githubusercontent.com/2290904/193447982-d3002294-e4be-4d0c-8a4b-d7f81c120572.png)

My TV is a UE55KU6000

**Comment by jeppevinkel** [comment]
I'm pretty sure that TV is too old. From what I can see your TV model is from 2016 and only on Tizen 2.4.

I have in the past tried and failed to get it uploaded to an old TV. I don't think I've yet been successful on any TV below Tizen 4.

It does seem some people have managed to install on Tizen 2.4 TVs, so you might find a solution in this thread https://github.com/jellyfin/jellyfin-tizen/issues/19#issuecomment-629785822, but unfortunately I can't help much more as I don't have access to any old TVs to test on.
