### ISSUE TITLE
Failed to construct 'Headers' - still the case with 2024-05-20 16:47 build

### ISSUE THREAD

**Issue by Hansaplast** [jeppevinkel/jellyfin-tizen-builds#41]
The build from  [2024-05-20 16:47](https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-05-20-1647) still has the "Failed to construct 'Headers': No matching constructor signature." error.
Test Jellyfin.wgt and Jellyfin-master.wgt, including removing previous installs, restarting the TV etc.

TV: Samsung UM82MU8000, Tizen 3.

I did see this being looked into, thought it would be good to mention it here.

**Comment by jeppevinkel** [comment]
The fix is only present in the prerelease build

**Comment by Hansaplast** [comment]
Thanks! Then I'll go try that one 😁  (I tend to avoid the prerelease since I have no idea what it may be or not - shortcoming on my end 😉 ).

p.s. I experienced this issue with all builds from this month, which you already knew, but an old one from November last year worked just fine. Having said that: the old version is 45 Mb, and all the failing ones are app. 10 Mb ... not sure if that is of any significance. Just thought I'd mention it 😊 

Thanks again for all the hard work!

**Comment by jeppevinkel** [comment]
They are supposed to be around 10 Mb. The 45 Mb versions are only that large due to an error on my part.

I usually don't use prerelease builds either, but the fix for the header issue hasn't made it to a full build yet. I'll restructure the prerelease/master naming soon though to make it easier to find a proper version.

**Comment by Hansaplast** [comment]
I did see, after you had mentioned it, that the releases actually stated that the fix was only in the prereleases available - so that was my bad. I'll go give your new release a try as soon as possible.
Thank you again for all the good work!

**Comment by Hansaplast** [comment]
p.s. Jellyfin -10.9.z.wgt works 😊 -- thanks! 😁

**Comment by themaluxis** [comment]
@jeppevinkel can you build secondary using 10.9.z ? would be great <3

**Comment by jeppevinkel** [comment]
> @jeppevinkel can you build secondary using 10.9.z ? would be great <3

Added one now in this release https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-05-22-1841
