### ISSUE TITLE
Jellyfin 10.9.6 Secondary Subtitles feature doesn't work properly

### ISSUE THREAD

**Issue by mjeshurun** [jeppevinkel/jellyfin-tizen-builds#44]
Hi @jeppevinkel 

I think there might be a bug with the new Secondary Subtitles feature on Jellyfin Tizen. 
I tried to use it, but whenever I choose the second subtitles language, the first language disappears from the screen and only the second subtitles language is shown.

On my desktop computer and iOS device both subtitles are properly shown together.

**Comment by jeppevinkel** [comment]
Issues with the app itself should be reported on https://github.com/jellyfin/jellyfin-tizen
