### ISSUE TITLE
Jellyfin only shows clock and greyish page at start

### ISSUE THREAD

**Issue by Madaraxa** [jeppevinkel/jellyfin-tizen-builds#45]
Hi,
i use your build for some time now (I started some weeks before you added the "secondary" and "trueHD" builds) and everything worked "ok".
I just had to reinstall jellyfin Server completely and updated the jellyfin-tizen builds as well (uninstalled them from my two samsung TVs and reinstalled).
At the jellyfin start on both TVs i only see the clock in the top right corner inside a bright grey bar and the rest of the screen stays greyish. I guess it is because I use the same IP and port on the new Jellyfin Server as I did on the "saved" one on the TVs and some sort of cache didnt get deleted on the TVs? So they try to connect to an old Jellyfin server and dont show the login page again?
I updated (deleted andd installed) to the latest "Jellyfin.wgt" and my server is on 10.9.6

**Comment by jeppevinkel** [comment]
If you are on the latest jellyfin server, then I'd recommend trying the `Jellyfin-10.9.z.wgt` build. If your TV is from 2017 or older, then I'd recommend trying the `Jellyfin-10.8.z.wgt` build.

**Comment by Madaraxa** [comment]
I'm on latest Server AND my TVs are from 2016 I think (K Series). So I should try 10.8.z right?

**Comment by jeppevinkel** [comment]
I can't make promises since success seems to vary a lot, but I've seen a few people on older TV's (pre 2019) that have only had success with the 10.8.z version.

**Comment by Madaraxa** [comment]
Yeah, thanks :) it works with 10.8.z

**Comment by burci** [comment]
Thank you! Only the 10.8.z worked for me as well!

(I have a KS7000 model from 2016.)
