### ISSUE TITLE
Audio Stuttering OPUS

### ISSUE THREAD

**Issue by Eloye23** [jeppevinkel/jellyfin-tizen-builds#47]
Audio stutters when playing opus format. Any fix?

**Comment by jeppevinkel** [comment]
I'm not sure. For issues during use, you should ask in https://github.com/jellyfin/jellyfin-tizen since that's where actual development of the app takes place. Any chance your issue could be related to https://github.com/jellyfin/jellyfin-tizen/issues/130?

**Comment by Eloye23** [comment]
> I'm not sure. For issues during use, you should ask in https://github.com/jellyfin/jellyfin-tizen since that's where actual development of the app takes place. Any chance your issue could be related to [jellyfin/jellyfin-tizen#130](https://github.com/jellyfin/jellyfin-tizen/issues/130)?

I just tested by playing through usb and it also stutters. I guess this tv just doesnt support opus format.
