### ISSUE TITLE
issues with installation

### ISSUE THREAD

**Issue by sebbe662** [jeppevinkel/jellyfin-tizen-builds#5]
i am getting an error where Powershell dose not recognise the comand "tizen" for some reason that i can not figure out. hope you can help.
![Screenshot 2022-12-26 010157](https://user-images.githubusercontent.com/77643776/209485110-731403dd-6a93-42e7-adb7-f8a3c4e2b293.png)

**Comment by evlo** [comment]
```
cd C:\tizen-studio\tools\ide\bin
.\tizen ...
```

**Comment by jeppevinkel** [comment]
Seems this was figured out in the comments, so just closing this as solved.
