### ISSUE TITLE
Question: When are there Updates for 10.8?

### ISSUE THREAD

**Issue by Madaraxa** [jeppevinkel/jellyfin-tizen-builds#50]
Hi,
I have a pretty old Samsung Tizen running jellyfin 10.8.
As there are a lot of Updates where the changelog mainly says 'new commit to 10.9' I never Update (correct?).
The latest Release states 'new commit to web'. Is that an Update that also changes the 10.8 Release?
Thanks in advance

**Comment by jeppevinkel** [comment]
I don't expect any updates to 10.8 any more since the Jellyfin team generally moves on after every new major version change, so once 10.9 comes out, 10.8 stops and now that 10.10 came out, 10.9 stops.
