### ISSUE TITLE
Invalid certificate chain on first install

### ISSUE THREAD

**Issue by tmiku** [jeppevinkel/jellyfin-tizen-builds#52]
I'm gettting the following error when installing the standard Jellyfin.wgt for the first time:
```
Installing the package...
--------------------
Platform log view
--------------------
install AprZAARz4r.Jellyfin
package_path /home/owner/share/tmp/sdk_tools/tmp/Jellyfin.wgt
app_id[AprZAARz4r.Jellyfin] install start
app_id[AprZAARz4r.Jellyfin] installing[9]
app_id[AprZAARz4r.Jellyfin] installing[19]
app_id[AprZAARz4r.Jellyfin] install failed[118, -12], reason: Check certificate error : :Invalid certificate chain with certificate in signature.:<-3>
spend time for wascmd is [6257]ms
Failed to install Tizen application.
Total time: 00:00:08.703
```
The documentation says to delete Jellyfin from the tv, but this is my first install. Do I need to go through the certificate setup described at [https://github.com/jellyfin/jellyfin-tizen](https://github.com/jellyfin/jellyfin-tizen), or is there something wrong with the latest .wgt uploaded? Is there a way to clear out old certificates if a Jellyfin app isn't visible on the TV?

**Comment by jeppevinkel** [comment]
This issue is specific to certain TVs. The only known solution is what's described here https://github.com/Georift/install-jellyfin-tizen/issues/21#issuecomment-2265138148

**Comment by tmiku** [comment]
Thank you, I have one of the models listed in the linked issue (DU7200D) and I was able to re-sign Jellyfin.wgt with my own certificate. That's a neat trick!
