### ISSUE TITLE
Wrong repository?

### ISSUE THREAD

**Issue by morpheus133** [jeppevinkel/jellyfin-tizen-builds#54]
Why Bobby306/jellyfin-web is used here:
https://github.com/jeppevinkel/jellyfin-tizen-builds/blob/d9eb036801ba8a18fb267b88161d219ecb4a2776/.github/workflows/build-new-release.yml#L92

All other places 'inject_intros: true' is set for adding intro support.

**Comment by jeppevinkel** [comment]
I think I forgot to change that place. I used to use Bobby306/jellyfin-web before it became obsolete.

Thanks for pointing it out, I'll fix it.

**Comment by jeppevinkel** [comment]
This new release now uses the latest release of jellyfin-web with this intro-skipper interface https://github.com/intro-skipper/intro-skipper  

https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-09-29-1903
