### ISSUE TITLE
How to display package's version installed on TV and in Jellyfin's dashboard ?

### ISSUE THREAD

**Issue by Broukmiken** [jeppevinkel/jellyfin-tizen-builds#56]
Hello,
first i want to thank you so much for your job
it's so easy to install :)
i wonder if there is a way to get the package version installed on the Samsung TV directly on the app screen of the TV ?
Or with tizen studio ?
bebause i don't know if each time i install the package it overwrite and update the previous one ...or not
thanks you for your advice.

**Comment by jeppevinkel** [comment]
There's not really a way right. The different packages don't really have version numbers because there's no official release versions.
You should be able to assume it has overwritten the old package if the console output doesn't show any errors.

**Comment by Broukmiken** [comment]
thanks for you answer.
it could be helpfull to have an "about" item directly in the App or somewhere to check what is running on the TV 🥇 

the only other way is just to see on the server, and this is what i see 
![Capture d'écran 2024-11-10 225843](https://github.com/user-attachments/assets/473c4302-3a15-4a29-9cc5-4ae743329e05)

**Comment by jeppevinkel** [comment]
The issue is there are no official releases of the app, so there is not version number to use.

**Comment by Broukmiken** [comment]
wha about overwritting on the icon ?
i've just compiled my own JellyfinTizen and it does the trick 👍 

![icon](https://github.com/user-attachments/assets/3b8c24d7-de06-45b7-aa1c-8c697c8b578b)

![Jellyfin_Tizen](https://github.com/user-attachments/assets/9c20280b-293f-456e-bb6a-25bd9fe7c8cd)

**Comment by jeppevinkel** [comment]
I will see if I can somehow inject the version into the UI somehow. I have tried adding an experimental change to at least replace the 0.1.0 version of the client with the current date in the form of year.month.day. We'll see if that works the next time a new release is made.

**Comment by Broukmiken** [comment]
Hello,
yes i saw that in your latest release 
you have changed the config.xml and it works
i tried to just add text instead of digits in this version tab but it doesn't work
because it would have been more readable to edit this tab with something like "compiled by... with Tizen xxx "
but thanks so much taking time to this

![config](https://github.com/user-attachments/assets/0420a137-7d1d-427a-8978-8610a10fd2bb)

**Comment by Broukmiken** [comment]
By editing :
config.xml

**Comment by jeppevinkel** [comment]
> By editing : config.xml Icon.png Tizen.js Located in jellyfin tizen directory I have compiled and things looks good on both TV and Jellyfin's server dashboard
> 
> ![20241119_232314.jpg](https://private-user-images.githubusercontent.com/109454001/387867935-afbc24ff-a4ea-4584-8400-3e0893a4dc29.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjQwNzgsIm5iZiI6MTczMjA2Mzc3OCwicGF0aCI6Ii8xMDk0NTQwMDEvMzg3ODY3OTM1LWFmYmMyNGZmLWE0ZWEtNDU4NC04NDAwLTNlMDg5M2E0ZGMyOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMDQ5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNTkwOTQ4ZWE1NzNkNzc5ODZiM2Q0NTlmZGU1M2EyOWIzZmQ3NTliZTAxN2I5YTlmMzFlYWE0M2M0N2ZkOTQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.opoZhZ-Sy8otqxglXWMcIKm2mA3cSWsxTT-m36JR4-Q)
> 
> ![20241120_000044.jpg](https://private-user-images.githubusercontent.com/109454001/387867955-d0b891a7-73de-4f41-a7ff-2900f1c4a7bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNjQwNzgsIm5iZiI6MTczMjA2Mzc3OCwicGF0aCI6Ii8xMDk0NTQwMDEvMzg3ODY3OTU1LWQwYjg5MWE3LTczZGUtNGY0MS1hN2ZmLTI5MDBmMWM0YTdiYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMFQwMDQ5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODljMzczZGM3YTg3YTJiYmU5NThhYWQxM2FlOWMzZmJiMjNjMjM1NzllOWFkNzE4NjM5NTYyYjU3ZTQwOTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.9rbPVsBXIizWqi1Ki16RSWZMhfYT34jNikTPCFxlomY)

Which value did you modify to make the custom text show on the dashboard?

**Comment by Broukmiken** [comment]
![config](https://github.com/user-attachments/assets/55684f92-748a-49b7-ab45-10c784546a8c)


![Capture d'écran 2024-11-20 092004](https://github.com/user-attachments/assets/796af27c-b62f-4eee-8518-6b85bd1426b7)

**Comment by Broukmiken** [comment]
![Capture d'écran 2024-11-20 091932](https://github.com/user-attachments/assets/94ea2807-9d9d-4664-a5b9-c9bb38a85965)



![Capture d'écran 2024-11-20 092004](https://github.com/user-attachments/assets/3df47c65-e624-4b67-bb2b-317a1604087c)

**Comment by jeppevinkel** [comment]
How about this then?
![image](https://github.com/user-attachments/assets/f5435d2e-b9b2-4bd9-ac9e-6dc4e8ed8b60)

![image](https://github.com/user-attachments/assets/58f27d9c-04f8-4267-aef6-f910d6bf776b)

**Comment by jeppevinkel** [comment]
That makes it both visible inside the app and from the dashboard. I probably won't modify the logo with text.

**Comment by Broukmiken** [comment]
It looks great

**Comment by jeppevinkel** [comment]
> It looks great

Okay, this is in the build pipeline, so I'll just close this issue as completed.

**Comment by Broukmiken** [comment]
hi,
in previous version , this mod was done in jellyfin-web\src\controllers\user\menu\index.html

i searched in latest 12.1 , this index.html has been removed.
do you know how to do the trick with the new version ?
thanks ;)

<img width="1325" height="765" alt="Image" src="https://github.com/user-attachments/assets/35221d52-9f46-4811-80d4-c1e7aa662174" />

**Comment by jeppevinkel** [comment]
> hi, in previous version , this mod was done in jellyfin-web\src\controllers\user\menu\index.html
> 
> i searched in latest 12.1 , this index.html has been removed. do you know how to do the trick with the new version ? thanks ;)
> <img alt="Image" width="1325" height="765" src="https://private-user-images.githubusercontent.com/109454001/655104127-35221d52-9f46-4811-80d4-c1e7aa662174.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3OTAwMDY3NTksIm5iZiI6MTc5MDAwNjQ1OSwicGF0aCI6Ii8xMDk0NTQwMDEvNjU1MTA0MTI3LTM1MjIxZDUyLTlmNDYtNDgxMS04MGQ0LWMxZTdhYTY2MjE3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwOTIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDkyMVQxNjAwNTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTdjYjUzY2NmNDhiNDI5ZjczOWYwZmExZTFjOGU1YmFhOWU2NzQ3ODI3Njc0NjQ3MTY4ZWU3ZjQ1NWY5YTUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.dkrKBDbA6XcCO888RBC74-wzMSKGoSAa9JrocjvYYGU">

I haven't updated my TV in a while because I don't have internet in my house currently (and won't until near the end of October), but my pipeline currently expects the file in either `src/apps/stable/routes/user/settings/index.tsx` or `src/apps/legacy/routes/user/settings/index.tsx` or `src/controllers/user/menu/index.html` depending on which version of jellyfin-web it installs. I just have it progressively check for each of the files like this:
```bash
if [ -f "src/controllers/user/menu/index.html" ]; then
  _found=1
  sed -i "s/<h2 class=\"sectionTitle headerUsername\" style=\"padding-left:.25em;\"><\/h2>/<h2 class=\"sectionTitle headerUsername\" style=\"padding-left:.25em;\"><\/h2><h4 style=\"padding-left:.25em;\">${{ matrix.artifact_name }} compiled ${{ needs.run-info.outputs.date }}<\/h4>/g" src/controllers/user/menu/index.html
fi

if [ -f "src/apps/legacy/routes/user/settings/index.tsx" ]; then
  _found=1
  sed -i -z "s/{user.Name}\n                        <\/h2>/{user.Name}\n                        <\/h2><h4 style={{paddingLeft:'0.25em'}}>${{ matrix.artifact_name }} compiled ${{ needs.run-info.outputs.date }}<\/h4>/g" src/apps/legacy/routes/user/settings/index.tsx
fi

if [ -f "src/apps/stable/routes/user/settings/index.tsx" ]; then
  _found=1
  sed -i -z "s/{user.Name}\n                        <\/h2>/{user.Name}\n                        <\/h2><h4 style={{paddingLeft:'0.25em'}}>${{ matrix.artifact_name }} compiled ${{ needs.run-info.outputs.date }}<\/h4>/g" src/apps/stable/routes/user/settings/index.tsx
fi
```
