### ISSUE TITLE
Crunchyroll for tizen? 

### ISSUE THREAD

**Issue by Nexow91** [jeppevinkel/jellyfin-tizen-builds#7]
Hi I'm hope I'm right here to write to you. Otherwise sry. Is it perhaps also possible to develop a crunchyroll for tizen there is still a großed need since samsung or crunchy roll has no app for it.

I would be happy to receive a reply.

PS: The jellifin app I find great has also worked well

**Comment by jeppevinkel** [comment]
That's unfortunately not something I can help with.
Unless crunchyroll has an open API to build apps and stream from their service, they are the only ones who can make an app like that.
