### ISSUE TITLE
tizen.bat not opening

### ISSUE THREAD

**Issue by LiamvdBerg** [jeppevinkel/jellyfin-tizen-builds#8]
When I open the tizen.bat for the installation it immediately closes after I double click. Do you have a solution?

**Comment by stripeytofu** [comment]
I'm having the same issue.

**Comment by jeppevinkel** [comment]
tizen.bat can't be opened. It's only meant for CLI operations. Commands run from the terminal.

If you open the folder containing tizen.bat, you can run commands like `./tizen.bat install -n Jellyfin.wgt -t <the name of your tv>`

**Comment by stripeytofu** [comment]
Thank you! This worked! I think I needed the "./" at the beginning of the command. It wasn't working before.
