### ISSUE TITLE
Build an app with a different name so i can use them with different accounts

### ISSUE THREAD

**Issue by Cavonzio** [jeppevinkel/jellyfin-tizen-builds#9]
Basically i'm asking if is it possible to have an app with a different name so i can install two versions of the app and login with two different jellyfin accounts so i dont have to logout and login every time i want to switch from one account to the other

**Comment by jeppevinkel** [comment]
I'm not sure how much work this would entail as I haven't looked at modifying the app like this before. I might look at it if I get some time one of the days, but I can't make any promises.

**Comment by Cavonzio** [comment]
Ok, no problem, thank you for your builds by the way, they saved me so much time compiling and deploying to my TV

**Comment by jeppevinkel** [comment]
Sorry for the very long wait. I have now gotten this working. The file called `Jellyfin-secondary.wgt` will show up as `Jellyfin-2` on the TV with an altered icon to make it easier to recognize. https://github.com/jeppevinkel/jellyfin-tizen-builds/releases/tag/2024-04-30-1704
